apiVersion: v1
kind: Service
metadata:
  name: resume-api
  namespace: gay-tcazier-api
spec:
  type: ClusterIP
  selector:
    app: resume-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-api
  namespace: gay-tcazier-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-api
  template:
    metadata:
      labels:
        app: resume-api
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: resume-api
        image: registry.gitlab.com/beanies-resume-website/api/api
        ports:
        - containerPort: 8080
        resources:
#           requests:
#           - memory: "64Mi"
#             cpu: "250m"
#           limits:
#           - memory: "128Mi"
#             cpu: "500m"
#         readinessProbe:
#           httpGet:
#             path: /readiness
#             port: 8080
#           initialDelaySeconds: 5
#           timeoutSeconds: 2
#           periodSeconds: 5
#           successThreshold: 1
#         livenessProbe:
#         - httpGet:
#           - path: /liveness
#             port: 8080
#           initialDelaySeconds: 5
#           timeoutSeconds: 2
#           periodSeconds: 5
#           failureThreshold: 1
#         startupProbe:
#           httpGet:
#           - path: /startup
#             port: 8080
#           initialDelay: 5
#           timeoutSeconds: 2
#           periodSeconds: 5
#           failureThreshold: 1